-- DROP TABLE IF EXISTS SONG;
--
-- CREATE TABLE IF NOT EXISTS SONG
-- (
--     ID     BIGSERIAL PRIMARY KEY,
--     ARTIST VARCHAR(255) NOT NULL,
--     NAME   VARCHAR(255) NOT NULL
-- )

-- niepotrzebne z uwagi na Hibernate