CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

ALTER TABLE USERS
    ADD CREATED_ON TIMESTAMP(6) WITH TIME ZONE DEFAULT NOW();

ALTER TABLE USERS
    ADD UUID UUID DEFAULT UUID_GENERATE_V4() NOT NULL UNIQUE;

ALTER TABLE USERS
    ADD VERSION BIGINT DEFAULT 0;

ALTER TABLE USERS
    ALTER COLUMN VERSION SET NOT NULL;