INSERT INTO ARTIST (NAME)
VALUES ('The Beatles'),
       ('Pink Floyd'),
       ('AC/DC'),
       ('Michael Jackson'),
       ('Eagles'),
       ('Fleetwood Mac'),
       ('Led Zeppelin'),
       ('Bruce Springsteen'),
       ('Nirvana'),
       ('Prince'),
       ('U2'),
       ('Guns N'' Roses'),
       ('Elton John'),
       ('The Rolling Stones'),
       ('Queen'),
       ('Simon & Garfunkel'),
       ('Meat Loaf'),
       ('David Bowie'),
       ('The Who'),
       ('Bob Dylan');
