INSERT INTO ARTIST_ALBUMS (ALBUMS_ID, ARTISTS_ID)
VALUES (1, 1),  -- 'Abbey Road' -> 'The Beatles'
       (2, 2),  -- 'The Dark Side of the Moon' -> 'Pink Floyd'
       (3, 3),  -- 'Back in Black' -> 'AC/DC'
       (4, 4),  -- 'Thriller' -> 'Michael Jackson'
       (5, 5),  -- 'Hotel California' -> 'Eagles'
       (6, 6),  -- 'Rumours' -> 'Fleetwood Mac'
       (7, 2),  -- 'The Wall' -> 'Pink Floyd'
       (8, 7),  -- 'Led Zeppelin IV' -> 'Led Zeppelin'
       (9, 8),  -- 'Born to Run' -> 'Bruce Springsteen'
       (10, 9), -- 'Nevermind' -> 'Nirvana'
       (11, 10),-- 'Purple Rain' -> 'Prince'
       (12, 11),-- 'The Joshua Tree' -> 'U2'
       (13, 12),-- 'Appetite for Destruction' -> 'Guns N\' Roses'
       (14, 1), -- 'Sgt. Pepper\'s Lonely Hearts Club Band' -> 'The Beatles'
       (15, 19),-- 'Who\'s Next' -> 'The Who'
       (16, 14),-- 'A Night at the Opera' -> 'Queen'
       (17, 15),-- 'Sticky Fingers' -> 'The Rolling Stones'
       (18, 13),-- 'Goodbye Yellow Brick Road' -> 'Elton John'
       (19, 16),-- 'Bridge Over Troubled Water' -> 'Simon & Garfunkel'
       (20, 17);-- 'Bat Out of Hell' -> 'Meat Loaf'
