ALTER TABLE ALBUM
    ADD version BIGINT DEFAULT 0;

ALTER TABLE ARTIST
    ADD version BIGINT DEFAULT 0;

ALTER TABLE GENRE
    ADD version BIGINT DEFAULT 0;

ALTER TABLE SONG
    ADD version BIGINT DEFAULT 0;