ALTER TABLE ALBUM
    ADD created_on TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT now();

ALTER TABLE ALBUM
    ADD uuid UUID DEFAULT uuid_generate_v4() NOT NULL UNIQUE;

ALTER TABLE ARTIST
    ADD created_on TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT now();

ALTER TABLE ARTIST
    ADD uuid UUID DEFAULT uuid_generate_v4() NOT NULL UNIQUE;

ALTER TABLE GENRE
    ADD created_on TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT now();

ALTER TABLE GENRE
    ADD uuid UUID DEFAULT uuid_generate_v4() NOT NULL UNIQUE;